const express = require('express');
const controller = require('../controllers/entregaController');
const service = require('../services/entregaService');
const router = express.Router();
router.get('/entregas', controller.list);
router.get('/entregas/:id', controller.get);
router.post('/entregas', controller.create);
router.put('/entregas/:id/status', async (req, res, next) => { try { const { ok } = require('../utils'); ok(res, await service.updateStatus(req.params.id, req.body.status), 'Status atualizado com sucesso'); } catch (e) { next(e); } });
router.put('/entregas/:id', controller.update);
router.delete('/entregas/:id', controller.remove);
module.exports = router;
